name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . --file docker/Dockerfile --tag username/webapp:latest

    - name: Push Docker image
      run: docker push username/webapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into VPS
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        script: |
          cd /var/www/webapp && git pull
          docker-compose down
          docker-compose up -d --build
